[project]
name = "DeepThrottle"
version = "0.1.0"
description = "A implementation of different rate limiting strategies for HTTP requests"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pydantic>=2.13.5",
    "uvicorn>=0.52.4",
]

[project.scripts]
deepthrottle = "deepthrottle.__main__:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"
